### PR TITLE
Raspberry tutorial review

### PR DESCRIPTION
**Pull request by desrever-nu**
I reviewed the tutorial and I believe is not ready for a merge

### CODE REVIEW

**Comment by CoinGame** [comment]
I unfortunately won't have time to run through and test the accuracy of the information. Have you run this PR by anyone on the forum that has done the setup, or did you do this all yourself while writing it?

**Comment by brossi** [comment]
> I reviewed the tutorial and I believe is not ready for a merge

**Not** or **Now**?

**Comment by desrever-nu** [comment]
is "now" ready -  sorry @brossi

**Comment by desrever-nu** [comment]
> Have you run this PR by anyone on the forum that has done the setup, or did you do this all yourself while writing it? 
> @CoinGame , I have followed myself the steps while compiling .

**Comment by desrever-nu** [comment]
Ok, I ran through it, applied some changes and waiting for others to comment ...
Before merging, a couple of things still are needed ...

@CoinGame @brossi 
- from daemon how can I list my receive NSR addresses?

**Comment by brossi** [comment]
### listreceivedbyaddress

`listreceivedbyaddress [minconf=1] [includeempty=false]`

[minconf] is the minimum number of confirmations before payments are included. Run against an individual unit (so you'll need to specify whether or not you want this to be for NBT or NSR address with the `-unit=B` or `-unit=S` command).

**Comment by desrever-nu** [comment]
Thanks !

**Comment by desrever-nu** [comment]
I have not received additional feedback, I think we can merge @brossi  @CoinGame

**Pull request merged**
